/**
 * EcoVolt Localization & Translation Hook
 * Supports English and Hindi (हिन्दी) across the entire application.
 */

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import * as SecureStore from 'expo-secure-store';

export type LanguageCode = 'en' | 'hi';

const LANGUAGE_STORAGE_KEY = 'ecovolt_language_preference';

// Comprehensive English -> Hindi Dictionary covering all UI terms in EcoVolt Finder
export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Tab Navigation
    'tab.home': 'Home',
    'tab.reservations': 'Reservations',
    'tab.saved': 'Saved',
    'tab.profile': 'Profile',
    'tab.leaderboard': 'Leaderboard',

    // Profile Screen & Headers
    'profile.title': 'Profile',
    'profile.verified_driver': 'Verified EcoVolt Driver',
    'profile.edit': 'Edit',
    'profile.green_tier': 'GREEN DRIVER TIER',
    'profile.green_pts': 'Green Pts',
    'profile.rank': 'Rank',
    'profile.clean_power': 'Clean Power',
    'profile.co2_saved': 'CO₂ Saved',
    'profile.eco_impact_standing': 'Eco Impact & Standing',
    'profile.leaderboard_green_score': 'Leaderboard & Green Score',
    'profile.view_rankings': 'View Rankings',
    'profile.badges_achievements': 'Badges & Achievements',
    'profile.unlocked': 'Unlocked',
    'profile.badges': 'Badges',
    'profile.live_grid': 'West India · IN-WE Grid',
    'profile.renewable_now': 'Renewable now',
    'profile.carbon_free': 'carbon-free',
    'profile.lifetime_impact': 'Your Lifetime Green Impact',
    'profile.co2_avoided': 'CO₂ avoided',
    'profile.from_renewables': 'from renewables',
    'profile.saved_green_windows': 'saved (green windows)',
    'profile.solar': 'Solar',
    'profile.wind': 'Wind',
    'profile.hydro': 'Hydro',
    'profile.coal_gas': 'Coal+Gas',
    
    // Workspace Portals
    'portal.title': 'Workspace Portals',
    'portal.station_manager': 'Station Manager Hub',
    'portal.station_manager_desc': 'Occupancy & Pricing',
    'portal.admin_console': 'Network Admin Console',
    'portal.admin_console_desc': 'Network Health',

    // Account Section
    'account.title': 'Account',
    'account.edit_profile': 'Edit Profile',
    'account.personal_info': 'Personal Info',
    'account.my_vehicles': 'My Vehicles',
    'account.no_vehicles': 'No Vehicles',
    'account.payment_methods': 'Payment Methods',
    'account.upi_wallet': 'UPI / Wallet',
    'account.charging_history': 'Charging History',

    // Preferences Section
    'pref.title': 'Preferences',
    'pref.notifications': 'Notifications & Alerts',
    'pref.enabled': 'Enabled',
    'pref.appearance': 'Appearance & Theme',
    'pref.theme_sub': 'Dark / Light',
    'pref.language': 'Language',
    'pref.lang_name': 'English',

    // Support Section
    'support.title': 'Support & Legal',
    'support.help_center': 'Help Center & FAQ',
    'support.help_center_sub': 'Guides & Tips',
    'support.contact_us': 'Contact Us & 24/7 Hotline',
    'support.contact_sub': 'Support',
    'support.terms_privacy': 'Terms & Privacy Policy',
    'support.terms_sub': 'Legal',
    'support.sign_out': 'Sign Out',
    'support.sign_out_confirm': 'Are you sure you want to sign out?',
    'support.cancel': 'Cancel',
    'support.app_version': 'EcoVolt-finder v1.0.0',

    // Edit Profile Modal
    'edit_profile.title': 'Edit Profile',
    'edit_profile.save': 'Save',
    'edit_profile.full_name': 'Full Name',
    'edit_profile.enter_full_name': 'Enter your full name',
    'edit_profile.email_address': 'Email Address',
    'edit_profile.phone_number': 'Phone Number',
    'edit_profile.account_security': 'Account Security',
    'edit_profile.security_desc': 'Your email is used for booking confirmations and smart solar charging alerts.',
    'edit_profile.save_btn': 'Save Profile Changes',
    'edit_profile.success': 'Your profile details have been successfully saved.',
    'edit_profile.success_title': 'Profile Updated',

    // Payment Methods Modal
    'payment.title': 'Payment Methods',
    'payment.smart_wallet': 'EcoVolt Smart Wallet',
    'payment.auto_discount': 'AUTO-DISCOUNT',
    'payment.avail_balance': 'Available Balance',
    'payment.wallet_sub': 'Locked at renewable charging slot rates · 0% transaction fees',
    'payment.auto_pay': 'Auto-Pay Green Windows',
    'payment.auto_pay_desc': 'Instantly settle sessions from wallet to unlock max dynamic solar discounts',
    'payment.upi_accounts': 'UPI Accounts (VPA)',
    'payment.add_upi': '+ Add UPI',
    'payment.saved_cards': 'Saved Credit & Debit Cards',
    'payment.link_upi': 'Link New UPI ID',
    'payment.enter_upi': 'Enter your UPI ID (e.g. mobile@upi or username@bank)',
    'payment.link_upi_btn': 'Link UPI',
    'payment.set_default': 'Set Default',
    'payment.default_pill': 'DEFAULT',
    'payment.primary_pill': 'PRIMARY',

    // Appearance Modal
    'appearance.title': 'Appearance & Theme',
    'appearance.done': 'Done',
    'appearance.theme_mode': 'Theme Mode',
    'appearance.system_default': 'System Default',
    'appearance.system_desc': 'Syncs automatically with device settings',
    'appearance.dark_onyx': 'Dark Onyx (Eco Battery)',
    'appearance.dark_desc': 'High energy efficiency on OLED screens',
    'appearance.crisp_light': 'Crisp Daylight',
    'appearance.light_desc': 'Optimal contrast in bright outdoor sunlight',
    'appearance.eco_accent': 'Eco Accent Palette',
    'appearance.volt_emerald': 'Volt Emerald',
    'appearance.cyber_teal': 'Cyber Teal',
    'appearance.solar_gold': 'Solar Gold',
    'appearance.electric_indigo': 'Electric Indigo',
    'appearance.map_style': 'Live Charging Map Style',
    'appearance.eco_hybrid': 'Eco Hybrid Grid',
    'appearance.eco_hybrid_desc': 'Highlights renewable zones & solar charging clusters',
    'appearance.minimal': 'Minimalist Clean',
    'appearance.minimal_desc': 'Low distractions, fast rendering',
    'appearance.satellite': '3D Satellite Terrain',
    'appearance.satellite_desc': 'High-definition satellite overhead view',
    'appearance.high_contrast': 'High Contrast Live Grid',
    'appearance.contrast_desc': 'Enhances readability of dynamic greenness bands and tariff charts',

    // Language Modal
    'lang.title': 'Select Language',
    'lang.subtitle': 'Choose your preferred interface and tariff announcement language',
    'lang.english': 'English',
    'lang.hindi': 'हिन्दी (Hindi)',
    'lang.english_region': 'English (India) · National Default',
    'lang.hindi_region': 'हिन्दी (भारत) · राष्ट्रीय भाषा',
    'lang.saved_title': 'Language Updated',
    'lang.saved_desc': 'App language updated successfully.',

    // Help Center Modal
    'help.title': 'Help Center & FAQ',
    'help.search_placeholder': 'Search FAQs, charging tips, errors...',
    'help.roadside': '24/7 Roadside & Charger Support',
    'help.roadside_sub': 'Instant assistance for gun lock or station errors',
    'help.all_topics': 'All Topics',
    'help.green_pricing': '🌱 Green Pricing',
    'help.connectors': '🔌 Connectors',
    'help.billing': '💳 Billing',
    'help.troubleshooting': '🛠 Troubleshooting',
    'help.faq_title': 'Frequently Asked Questions',
    'help.still_questions': 'Still have questions?',
    'help.still_questions_desc': 'Our team is available 24/7 to help you with reservations, charger troubleshooting, and rebates.',
    'help.send_message': 'Send Us a Message',

    // Contact Us Modal
    'contact.title': 'Contact Support',
    'contact.hotline': '24/7 Hotline',
    'contact.email_support': 'Email Support',
    'contact.category_title': 'What is your inquiry regarding?',
    'contact.cat_charging': '⚡ Session & Charging',
    'contact.cat_billing': '💳 Billing & Discounts',
    'contact.cat_hardware': '🛠 Station & Connector',
    'contact.cat_general': '💬 General / Feedback',
    'contact.subject': 'Subject',
    'contact.description': 'Detailed Description',
    'contact.submit': 'Submit Support Request',
    'contact.success_title': 'Support Ticket Created!',
    'contact.back_profile': 'Back to Profile',

    // Home Screen
    'home.greeting': 'Hello',
    'home.subtitle': 'Find your nearest charging station',
    'home.search_placeholder': 'Search stations, locations...',
    'home.available_now': 'Available Now',
    'home.solar_green': 'Solar & Green Hours',
    'home.quick_book': 'Quick Book',
    'home.chargers_near_you': 'EV Chargers Near You',
    'home.view_all': 'View All',
    'home.filter': 'Filters',
    'home.renewable_grid': 'Renewable Grid',
    'home.tap_directions': 'Tap for Directions',

    // Reservations Screen
    'reservations.title': 'My Bookings & History',
    'reservations.active_tab': 'Active & Scheduled',
    'reservations.past_tab': 'Past Receipts',
    'reservations.no_active': 'No Active Reservations',
    'reservations.no_active_desc': 'Book a charging slot at your preferred station to guarantee availability.',
    'reservations.no_past': 'No Past Charging Sessions',
    'reservations.no_past_desc': 'Your completed charging sessions and receipts will appear here.',
    'reservations.find_stations': 'Find Charging Stations',
    'reservations.start_charging': '⚡ Start Charging',
    'reservations.cancel_booking': 'Cancel Reservation',
    'reservations.cancel_confirm': 'Are you sure you want to cancel this reservation?',
    'reservations.today': 'Today',
    'reservations.tomorrow': 'Tomorrow',
    'reservations.status_reserved': 'Reserved',
    'reservations.status_active': 'Charging Active',
    'reservations.status_completed': 'Completed',
    'reservations.status_cancelled': 'Cancelled',
    'reservations.status_expired': 'Expired',
    'reservations.locked_rate': 'Locked Rate',
    'reservations.total_billed': 'Total Billed',
    'reservations.view_station': 'View Station',

    // Saved Screen
    'saved.title': 'Saved Stations',
    'saved.subtitle': 'saved station(s)',
    'saved.no_saved': 'No Saved Stations',
    'saved.no_saved_desc': 'Bookmark your frequently used charging stations for quick access.',
    'saved.find_stations': 'Find Stations',
    'saved.remove_title': 'Remove Saved Station',
    'saved.remove_confirm': 'Remove this station from your saved list?',

    // Station Card & General Components
    'card.available': 'Available',
    'card.unavailable': 'Occupied',
    'card.book_slot': 'Book Slot',
    'card.from': 'From',
    'card.renewable': 'Renewable',
    'card.chargers': 'chargers',
    'card.reviews': 'reviews',
    'card.min': 'min',

    // Charging Screen
    'charging.title': 'Charging Session',
    'charging.ready': 'Ready to charge',
    'charging.in_progress': 'Charging in progress...',
    'charging.duration': 'Duration',
    'charging.energy': 'Energy',
    'charging.cost': 'Cost',
    'charging.charger_power': 'Charger Power',
    'charging.rate': 'Rate',
    'charging.est_range': 'Est. Range Added',
    'charging.clean_grid': 'Clean Energy Grid',
    'charging.co2_avoided': 'CO₂ Avoided',
    'charging.start_btn': '⚡ Start Charging Session',
    'charging.end_btn': 'End Charging Session',
    'charging.start_alert_title': 'Start Charging',
    'charging.start_alert_desc': 'Make sure your vehicle is properly connected to the charger before starting.',
    'charging.end_alert_title': 'End Charging Session',
    'charging.end_alert_desc': 'Are you sure you want to end your charging session now?',
    'charging.continue': 'Continue Charging',
    'charging.complete_title': 'Charging Complete! 🎉',
    'charging.complete_sub': 'Thank you for driving clean and powering the green revolution with EcoVolt! 🌿⚡',
    'charging.delivered': 'Delivered',
    'charging.total_cost': 'Total Cost',
    'charging.ecopoints': 'EcoPoints',
    'charging.receipt_note': 'A dynamic session receipt and sweet eco-credit alert have been saved in your notifications!',
    'charging.view_reservations': 'View All Reservations',
    'charging.go_home': 'Go to Home',

    // Station Detail Screen
    'station.details_title': 'Station Details',
    'station.saved': 'Saved',
    'station.save': 'Save',
    'station.loading': 'Loading station...',
    'station.not_found': 'Station not found',
    'station.go_back': 'Go Back',
    'station.photos_enlarge': 'Tap to enlarge',
    'station.no_photos': 'No photos available',
    'station.available_chargers': 'Available Chargers',
    'station.no_chargers': 'No chargers available',
    'station.distance': 'Distance',
    'station.min_drive': 'min drive',
    'station.rating': 'Rating',
    'station.amenities': 'Amenities',
    'station.get_directions': 'Get Directions',
    'station.live_greenness': 'Live Grid Greenness',
    'station.renewable': 'renewable',
    'station.carbon_free': 'Carbon-free',
    'station.carbon_intensity': 'Carbon intensity',
    'station.renewable_note': 'Renewable ≠ Carbon-free (nuclear excluded)',
    'station.grid_mix': 'Grid Mix Right Now',
    'station.forecast_24h': '24h Renewable Forecast',
    'station.best_window': 'Best window:',
    'station.forecast_saves': 'saves ~₹',
    'station.forecast_highlight': '◼ Highlighted = best charging window',
    'station.forecast_now': '◉ = Now',
    'station.reserve_now': 'Reserve Now',
    'station.base_tariff': 'Base tariff',
    'station.service_markup': 'Service markup',
    'station.green_discount_now': '🌿 Green discount (now)',
    'station.peak_surcharge': '⚡ Peak surcharge',
    'station.no_tou_adj': 'No ToU adjustment',
    'station.final_price': 'Final price',
    'station.estimate': 'estimate',
    'station.amenity.wifi': 'WiFi',
    'station.amenity.restrooms': 'Restrooms',
    'station.amenity.cafe': 'Café',
    'station.amenity.shopping': 'Shopping',
    'station.amenity.parking': 'Parking',
    'station.amenity.24h': '24/7 Access',
    'station.amenity.food_court': 'Food Court',

    // Reserve & Booking Screen
    'reserve.title': 'Reserve Charger',
    'reserve.loading_charger': 'Loading charger details...',
    'reserve.charger_not_found': 'Charger not found',
    'reserve.error_subtext': 'Please go back and try again',
    'reserve.select_vehicle': 'Select Vehicle',
    'reserve.add_vehicle': '+ Add Vehicle',
    'reserve.no_vehicles': 'No vehicles found in your garage.',
    'reserve.select_date': 'Select Date',
    'reserve.select_time': 'Select Start Time',
    'reserve.duration': 'Duration',
    'reserve.summary_title': 'Reservation Summary',
    'reserve.date': 'Date',
    'reserve.time': 'Time',
    'reserve.duration_label': 'Duration',
    'reserve.base_rate': 'Base rate',
    'reserve.green_discount': '🌿 Green discount',
    'reserve.peak_surcharge_label': '⚡ Peak surcharge',
    'reserve.effective_rate': 'Effective rate',
    'reserve.estimated_cost': 'Estimated Cost',
    'reserve.cost_note': 'Based on full duration at 85% charging efficiency',
    'reserve.confirm_btn': 'Confirm Reservation',
    'reserve.select_time_alert': 'Please select a start time for your reservation.',
    'reserve.no_vehicle_alert': 'Please add a vehicle to your profile before making a reservation.',
    'reserve.failed_alert': 'The time slot may already be taken or the charger is unavailable. Please try a different time.',
    'reserve.status_available': 'Available',
    'reserve.status_in_use': 'In Use',
    'reserve.status_reserved': 'Reserved',
    'reserve.status_offline': 'Offline',
    'reserve.status_maintenance': 'Maintenance',
    'reserve.type_dc_fast': 'DC Fast Charging',
    'reserve.type_level_2': 'Level 2 AC',
    'reserve.type_tesla': 'Tesla Supercharger',
    'reserve.green_active': '🌿 Green discount active — save',
    'reserve.peak_active': '⚡ Peak hour — surcharge',
    'reserve.standard_rate': '✓ Standard rate — no ToU adjustment',
    'reserve.not_selected': 'Not selected',
    // Filter & Navigation Modals
    'filter.title': 'Filters',
    'filter.reset': 'Reset',
    'filter.available_only': 'Available Chargers Only',
    'filter.available_desc': 'Show only stations with available chargers',
    'filter.max_distance': 'Maximum Distance',
    'filter.charger_type': 'Charger Type',
    'filter.connector_type': 'Connector Type',
    'filter.price_per_kwh': 'Price per kWh',
    'filter.amenities': 'Amenities',
    'filter.apply': 'Apply Filters',
    'nav.title': 'Navigation',
    'reservations.starts_now': 'Starts right now! Please arrive at station',
    'reservations.mins_remaining': 'minutes remaining in slot',
    'reservations.check_in_start': '⚡ Check In / Start Charging Session',
    'reservations.send_reminder': '🔔 Send Status Reminder',
    'reservations.book_again': 'Book Again',
    'reservations.cancel_alert_title': 'Cancel Reservation',
    'reservations.cancel_alert_msg': 'Are you sure you want to cancel this reservation? This action cannot be undone.',
    'reservations.keep_booking': 'Keep Reservation',
    'reservations.cancelled_success': 'Your reservation has been cancelled.',

    // Manager Console
    'manager.title': 'Station Manager Hub',
    'manager.title_short': 'Station Manager',
    'manager.online': 'ONLINE',
    'manager.telemetry_loading': 'Loading Manager Telemetry...',
    'manager.total_revenue': 'Total Station Revenue',
    'manager.clean_power_delivered': 'Clean Power Delivered',
    'manager.green_share': 'Green Share',
    'manager.utilization_rate': 'Network Utilization Rate',
    'manager.operational_status': 'Operational Status',
    'manager.managed_stations': 'Managed Stations',
    'manager.active_sessions': 'Active Charging Sessions',
    'manager.co2_avoided': 'Net CO₂ Emissions Avoided',
    'manager.hubs': 'Hubs',
    'manager.live_now': 'Live Now',
    'manager.onboard_station': '+ Onboard Charging Hub',
    'manager.station_name': 'Station Name',
    'manager.address': 'Address',
    'manager.connectors': 'Connectors',
    'manager.maintenance': 'Maintenance',
    'manager.available': 'Available',
    'manager.in_use': 'In Use',
    'manager.toggle_maintenance': 'Toggle Maintenance',
    'manager.pricing_rules_title': 'Station Pricing Rules & ToU Tariffs',
    'manager.pricing_rules_desc': 'Dynamic ToU Pricing & Dynamic Surge Markup',
    'manager.provider_base_rate': 'Base Rate',
    'manager.operator_markup': 'Operator Markup',
    'manager.final_driver_rate': 'Final Rate',
    'manager.dynamic_discount': 'Dynamic Discount',
    'manager.occupancy_threshold': 'Occupancy Threshold',
    'manager.add_pricing_rule': '+ Add Pricing Rule',
    'manager.edit_rule': 'Edit Rule',
    'manager.save_rule': 'Save Pricing Rule',
    'manager.payout_bank_details': 'Razorpay Payout Bank Details',
    'manager.payout_desc': 'Money collected from EV charging sessions is automatically settled to this account via Razorpay.',
    'manager.account_holder_name': 'Account Holder Name',
    'manager.bank_name': 'Bank Name',
    'manager.account_number': 'Account Number',
    'manager.ifsc_code': 'IFSC Code',
    'manager.alert_toggles': 'Alert & Notification Toggles',
    'manager.outage_alerts': 'Outage & Connector Offline Alerts',
    'manager.email_alerts': 'Email Settlement Summaries',
    'manager.save_payout_settings': '💾 Save Bank & Alert Settings',
    'manager.app_preferences': '🌐 App Preferences & Governance',
    'manager.app_language': 'App Language / भाषा',
    'manager.appearance_theme': 'Appearance Theme',
    'manager.sign_out': 'Sign Out',
    'manager.sign_out_confirm': 'Are you sure you want to log out of Station Manager?',
    'manager.force_stop': 'Force Stop',
    'manager.issue_refund': 'Issue Refund',
    'manager.free_stuck_connector': 'Free Stuck Connector',
    'manager.no_sessions': 'No Active Sessions',
    'manager.tab_analytics': 'Manager Hub',
    'manager.tab_sessions': 'Live Sessions',
    'manager.tab_pricing': 'Pricing Engine',
    'manager.tab_payout': 'Operator Profile',

    // Admin Console
    'admin.title': 'Network Admin Console',
    'admin.grid_online': 'GRID ONLINE',
    'admin.subtext': 'Platform Governance & Operational Audit Portal',
    'admin.loading': 'Fetching Executive Telemetry...',
    'admin.notice_title': 'Server-Enforced Read-Only Governance',
    'admin.notice_desc': 'Admin role enforces structural visibility over driver & manager data. Direct editing of station listings, pricing, or wallet funds remains with the owning manager.',
    'admin.live_load': 'Total Network Live Load',
    'admin.aggregate_green_share': 'Aggregate Green Share',
    'admin.gross_revenue': 'Platform Gross Revenue',
    'admin.green_shifts': 'Green Window Shifts',
    'admin.footprint_title': 'Platform Footprint & Data Sources',
    'admin.registered_users': 'Registered Users',
    'admin.operator_networks': 'Operator Networks',
    'admin.hub_registry': 'Station Hub Registry',
    'admin.data_quality': 'Data Source Quality',
    'admin.clean_methodology_title': 'Clean Energy Methodology & Classification',
    'admin.clean_methodology_desc': '• Hydro Classification: Large hydro-power is tracked separately from solar/wind to keep carbon accounting defensible.\n• Carbon-Free vs Renewable: Solar & wind count as 100% renewable; grid nuclear/hydro count toward carbon-free total.',
    'admin.search_stations_placeholder': '🔍 Search stations, address, or operator...',
    'admin.add_station': '+ Add Station',
    'admin.approved': 'APPROVED',
    'admin.deactivated': 'DEACTIVATED',
    'admin.pricing_readonly': 'Pricing (Read-Only)',
    'admin.flag_deactivate': '🚩 Flag / Deactivate',
    'admin.approve_activate': '✅ Approve & Activate',
    'admin.delete': '🗑️ Delete',
    'admin.search_users_placeholder': '🔍 Search users by name or email...',
    'admin.add_user': '+ Add User',
    'admin.govern_role': '🛡️ Govern Role',
    'admin.data_police_title': '📊 Platform Data Quality & Anomaly Police',
    'admin.live_feed': 'Live Rest API Feed',
    'admin.cached_snapshot': 'Cached Grid Snapshot',
    'admin.ml_forecast': 'ML Forecasted Share',
    'admin.anomalies_detected': '0 ANOMALIES DETECTED',
    'admin.system_ops_title': '⚡ System Ops Status',
    'admin.server_uptime': 'Express Server Uptime',
    'admin.postgres_latency': 'PostgreSQL Engine Latency',
    'admin.maps_quota': 'Google Maps API Quota Used',
    'admin.ml_worker': 'Background ML Prediction Worker',
    'admin.booking_worker': 'Background Booking Reminder Worker',
    'admin.app_preferences': '🌐 Admin Preferences & Governance',
    'admin.app_language': 'Platform Language / भाषा',
    'admin.appearance_theme': 'Appearance Theme',
    'admin.sign_out': 'Sign Out of Admin Account',
    'admin.sign_out_confirm': 'Are you sure you want to log out of Network Admin Console?',
    'admin.financials_title': '💰 Network Financial Aggregates',
    'admin.financials_sub': 'Financial telemetry is read-only. Admins oversee volume & dispute trends without direct wallet touching.',
    'admin.total_volume': 'Total Payment Volume',
    'admin.successful_tx': 'Successful Transactions',
    'admin.failed_tx_rate': 'Failed Transaction Rate',
    'admin.refund_total': 'Cumulative Refunds Processed',
    'admin.power_taxonomy': '⚙️ Power Provider Taxonomy',
    'admin.connector_taxonomy': '🔌 Connector Type Taxonomy',
    'admin.greenness_thresholds': '🌿 Greenness Band Thresholds',
    'admin.security_events_title': '🔒 Security Events & Auth Monitoring',
    'admin.failed_logins': 'Failed Login Attempts (24h)',
    'admin.signature_errors': 'Invalid Signature Errors',
    'admin.rate_limit_hits': 'Rate-Limit Trigger Count',
    'admin.tab_overview': 'Admin Hub',
    'admin.tab_registry': 'Station Registry',
    'admin.tab_users': 'User Governance',
    'admin.tab_zones': 'Grid & Quality',
    'admin.tab_health': 'System Ops',
    'admin.tab_financials': 'Financials',
    'admin.tab_config': 'Platform Config',
    'admin.tab_audit': 'Audit Trail',
  },
  hi: {
    // Tab Navigation
    'tab.home': 'होम',
    'tab.reservations': 'बुकिंग्स',
    'tab.saved': 'सहेजे गए',
    'tab.profile': 'प्रोफ़ाइल',
    'tab.leaderboard': 'लीडरबोर्ड',

    // Profile Screen & Headers
    'profile.title': 'प्रोफ़ाइल',
    'profile.verified_driver': 'सत्यापित इकोवोल्ट ड्राइवर',
    'profile.edit': 'संपादित करें',
    'profile.green_tier': 'ग्रीन ड्राइवर स्तर',
    'profile.green_pts': 'ग्रीन पॉइंट्स',
    'profile.rank': 'रैंक',
    'profile.clean_power': 'स्वच्छ ऊर्जा',
    'profile.co2_saved': 'CO₂ बचत',
    'profile.eco_impact_standing': 'पर्यावरण प्रभाव और स्थिति',
    'profile.leaderboard_green_score': 'लीडरबोर्ड और ग्रीन स्कोर',
    'profile.view_rankings': 'रैंकिंग देखें',
    'profile.badges_achievements': 'बैज और उपलब्धियां',
    'profile.unlocked': 'अनलॉक किया गया',
    'profile.badges': 'बैज',
    'profile.live_grid': 'पश्चिम भारत · IN-WE ग्रिड',
    'profile.renewable_now': 'नवीकरणीय ऊर्जा अभी',
    'profile.carbon_free': 'कार्बन-मुक्त',
    'profile.lifetime_impact': 'आपका आजीवन हरित प्रभाव',
    'profile.co2_avoided': 'CO₂ रोका गया',
    'profile.from_renewables': 'नवीकरणीय स्रोतों से',
    'profile.saved_green_windows': 'बचत (हरित समय)',
    'profile.solar': 'सोलर',
    'profile.wind': 'पवन',
    'profile.hydro': 'जलविद्युत',
    'profile.coal_gas': 'कोयला+गैस',

    // Workspace Portals
    'portal.title': 'वर्कस्पेस पोर्टल्स',
    'portal.station_manager': 'स्टेशन प्रबंधक हब',
    'portal.station_manager_desc': 'ऑक्यूपेंसी और दर निर्धारण',
    'portal.admin_console': 'नेटवर्क एडमिन कंसोल',
    'portal.admin_console_desc': 'नेटवर्क स्थिति',

    // Account Section
    'account.title': 'खाता',
    'account.edit_profile': 'प्रोफ़ाइल संपादित करें',
    'account.personal_info': 'व्यक्तिगत जानकारी',
    'account.my_vehicles': 'मेरे वाहन',
    'account.no_vehicles': 'कोई वाहन नहीं',
    'account.payment_methods': 'भुगतान विधियां',
    'account.upi_wallet': 'यूपीआई / वॉलेट',
    'account.charging_history': 'चार्जिंग इतिहास',

    // Preferences Section
    'pref.title': 'प्राथमिकताएं',
    'pref.notifications': 'सूचनाएं और अलर्ट',
    'pref.enabled': 'सक्षम',
    'pref.appearance': 'दिखावट और थीम',
    'pref.theme_sub': 'डार्क / लाइट',
    'pref.language': 'भाषा',
    'pref.lang_name': 'हिन्दी',

    // Support Section
    'support.title': 'सहायता और नियम',
    'support.help_center': 'सहायता केंद्र और प्रश्नोत्तर',
    'support.help_center_sub': 'गाइड और सुझाव',
    'support.contact_us': 'संपर्क करें और 24/7 हेल्पलाइन',
    'support.contact_sub': 'सहायता',
    'support.terms_privacy': 'नियम और गोपनीयता नीति',
    'support.terms_sub': 'कानूनी',
    'support.sign_out': 'साइन आउट करें',
    'support.sign_out_confirm': 'क्या आप वाकई साइन आउट करना चाहते हैं?',
    'support.cancel': 'रद्द करें',
    'support.app_version': 'EcoVolt-finder v1.0.0',

    // Edit Profile Modal
    'edit_profile.title': 'प्रोफ़ाइल संपादित करें',
    'edit_profile.save': 'सहेजें',
    'edit_profile.full_name': 'पूरा नाम',
    'edit_profile.enter_full_name': 'अपना पूरा नाम दर्ज करें',
    'edit_profile.email_address': 'ईमेल पता',
    'edit_profile.phone_number': 'फ़ोन नंबर',
    'edit_profile.account_security': 'खाता सुरक्षा',
    'edit_profile.security_desc': 'आपकी ईमेल का उपयोग बुकिंग पुष्टि और स्मार्ट सोलर चार्जिंग अलर्ट के लिए किया जाता है।',
    'edit_profile.save_btn': 'प्रोफ़ाइल परिवर्तन सहेजें',
    'edit_profile.success': 'आपकी प्रोफ़ाइल जानकारी सफलतापूर्वक सहेजी गई है।',
    'edit_profile.success_title': 'प्रोफ़ाइल अपडेट हुई',

    // Payment Methods Modal
    'payment.title': 'भुगतान विधियां',
    'payment.smart_wallet': 'इकोवोल्ट स्मार्ट वॉलेट',
    'payment.auto_discount': 'ऑटो-छूट',
    'payment.avail_balance': 'उपलब्ध बैलेंस',
    'payment.wallet_sub': 'नवीकरणीय चार्जिंग स्लॉट दरों पर लॉक · 0% लेनदेन शुल्क',
    'payment.auto_pay': 'ग्रीन विंडो में ऑटो-पे',
    'payment.auto_pay_desc': 'अधिकतम सोलर छूट पाने के लिए वॉलेट से तुरंत भुगतान करें',
    'payment.upi_accounts': 'यूपीआई खाते (VPA)',
    'payment.add_upi': '+ यूपीआई जोड़ें',
    'payment.saved_cards': 'सहेजे गए क्रेडिट और डेबिट कार्ड',
    'payment.link_upi': 'नया यूपीआई जोड़ें',
    'payment.enter_upi': 'अपना यूपीआई आईडी दर्ज करें (उदा. mobile@upi)',
    'payment.link_upi_btn': 'यूपीआई लिंक करें',
    'payment.set_default': 'डिफ़ॉल्ट बनाएं',
    'payment.default_pill': 'डिफ़ॉल्ट',
    'payment.primary_pill': 'मुख्य',

    // Appearance Modal
    'appearance.title': 'दिखावट और थीम',
    'appearance.done': 'पूर्ण',
    'appearance.theme_mode': 'थीम मोड',
    'appearance.system_default': 'सिस्टम डिफ़ॉल्ट',
    'appearance.system_desc': 'डिवाइस सेटिंग्स के अनुसार स्वचालित रूप से सिंक होता है',
    'appearance.dark_onyx': 'डार्क ओनिक्स (बैटरी बचत)',
    'appearance.dark_desc': 'OLED स्क्रीन पर उच्च ऊर्जा दक्षता',
    'appearance.crisp_light': 'उज्ज्वल दिन का प्रकाश (लाइट)',
    'appearance.light_desc': 'तेज धूप में सबसे स्पष्ट कंट्रास्ट',
    'appearance.eco_accent': 'इको एक्सेंट रंग',
    'appearance.volt_emerald': 'वोल्ट पन्ना (Emerald)',
    'appearance.cyber_teal': 'साइबर टील',
    'appearance.solar_gold': 'सोलर गोल्ड',
    'appearance.electric_indigo': 'इलेक्ट्रिक इंडिगो',
    'appearance.map_style': 'लाइव चार्जिंग मैप स्टाइल',
    'appearance.eco_hybrid': 'इको हाइब्रिड ग्रिड',
    'appearance.eco_hybrid_desc': 'नवीकरणीय क्षेत्रों और सौर चार्जिंग क्लस्टरों को हाइलाइट करता है',
    'appearance.minimal': 'मिनिमलिस्ट क्लीन',
    'appearance.minimal_desc': 'सरल और तेज़ रेंडरिंग',
    'appearance.satellite': '3D सैटेलाइट व्यू',
    'appearance.satellite_desc': 'उच्च गुणवत्ता वाला सैटेलाइट दृश्य',
    'appearance.high_contrast': 'उच्च कंट्रास्ट लाइव ग्रिड',
    'appearance.contrast_desc': 'ग्रिड और टैरिफ चार्ट की स्पष्टता बढ़ाता है',

    // Language Modal
    'lang.title': 'भाषा चुनें',
    'lang.subtitle': 'अपनी पसंदीदा इंटरफ़ेस भाषा चुनें',
    'lang.english': 'English (अंग्रेज़ी)',
    'lang.hindi': 'हिन्दी (Hindi)',
    'lang.english_region': 'English (India) · National Default',
    'lang.hindi_region': 'हिन्दी (भारत) · राष्ट्रीय भाषा',
    'lang.saved_title': 'भाषा अपडेट हो गई',
    'lang.saved_desc': 'ऐप की भाषा सफलतापूर्वक बदल दी गई है।',

    // Help Center Modal
    'help.title': 'सहायता केंद्र और प्रश्नोत्तर',
    'help.search_placeholder': 'प्रश्न, चार्जिंग टिप्स, त्रुटियां खोजें...',
    'help.roadside': '24/7 रोडसाइड और चार्जर सहायता',
    'help.roadside_sub': 'गन लॉक या स्टेशन त्रुटि के लिए त्वरित सहायता',
    'help.all_topics': 'सभी विषय',
    'help.green_pricing': '🌱 हरित मूल्य निर्धारण',
    'help.connectors': '🔌 कनेक्टर्स',
    'help.billing': '💳 बिलिंग',
    'help.troubleshooting': '🛠 समस्या निवारण',
    'help.faq_title': 'अक्सर पूछे जाने वाले प्रश्न',
    'help.still_questions': 'क्या आपके पास अब भी प्रश्न हैं?',
    'help.still_questions_desc': 'हमारी टीम बुकिंग और चार्जर समस्या निवारण के लिए 24/7 उपलब्ध है।',
    'help.send_message': 'हमें संदेश भेजें',

    // Contact Us Modal
    'contact.title': 'सहायता से संपर्क करें',
    'contact.hotline': '24/7 हेल्पलाइन',
    'contact.email_support': 'ईमेल सहायता',
    'contact.category_title': 'आपकी पूछताछ किस संबंध में है?',
    'contact.cat_charging': '⚡ सत्र और चार्जिंग',
    'contact.cat_billing': '💳 बिलिंग और छूट',
    'contact.cat_hardware': '🛠 स्टेशन और कनेक्टर',
    'contact.cat_general': '💬 सामान्य / फीडबैक',
    'contact.subject': 'विषय',
    'contact.description': 'विस्तृत विवरण',
    'contact.submit': 'सहायता अनुरोध सबमिट करें',
    'contact.success_title': 'सहायता टिकट बनाया गया!',
    'contact.back_profile': 'प्रोफ़ाइल पर वापस जाएं',

    // Home Screen
    'home.greeting': 'नमस्ते',
    'home.subtitle': 'अपना निकटतम चार्जिंग स्टेशन खोजें',
    'home.search_placeholder': 'स्टेशन, स्थान खोजें...',
    'home.available_now': 'अभी उपलब्ध',
    'home.solar_green': 'सौर और हरित समय',
    'home.quick_book': 'त्वरित बुकिंग',
    'home.chargers_near_you': 'आपके आस-पास ईवी चार्जर',
    'home.view_all': 'सभी देखें',
    'home.filter': 'फ़िल्टर',
    'home.renewable_grid': 'नवीकरणीय ग्रिड',
    'home.tap_directions': 'दिशा-निर्देश देखें',

    // Reservations Screen
    'reservations.title': 'मेरी बुकिंग्स और इतिहास',
    'reservations.active_tab': 'सक्रिय और निर्धारित',
    'reservations.past_tab': 'पिछली रसीदें',
    'reservations.no_active': 'कोई सक्रिय बुकिंग नहीं',
    'reservations.no_active_desc': 'उपलब्धता सुनिश्चित करने के लिए अपने पसंदीदा स्टेशन पर चार्जिंग स्लॉट बुक करें।',
    'reservations.no_past': 'कोई पिछला सत्र नहीं',
    'reservations.no_past_desc': 'आपके पूर्ण किए गए चार्जिंग सत्र और रसीदें यहां दिखाई देंगी।',
    'reservations.find_stations': 'चार्जिंग स्टेशन खोजें',
    'reservations.start_charging': '⚡ चार्जिंग शुरू करें',
    'reservations.cancel_booking': 'बुकिंग रद्द करें',
    'reservations.cancel_confirm': 'क्या आप वाकई इस बुकिंग को रद्द करना चाहते हैं?',
    'reservations.today': 'आज',
    'reservations.tomorrow': 'कल',
    'reservations.status_reserved': 'आरक्षित',
    'reservations.status_active': 'चार्जिंग सक्रिय',
    'reservations.status_completed': 'पूर्ण',
    'reservations.status_cancelled': 'रद्द किया गया',
    'reservations.status_expired': 'समाप्त',
    'reservations.locked_rate': 'लॉक की गई दर',
    'reservations.total_billed': 'कुल बिल',
    'reservations.view_station': 'स्टेशन देखें',

    // Saved Screen
    'saved.title': 'सहेजे गए स्टेशन',
    'saved.subtitle': 'सहेजे गए स्टेशन',
    'saved.no_saved': 'कोई सहेजा गया स्टेशन नहीं',
    'saved.no_saved_desc': 'त्वरित पहुंच के लिए अपने पसंदीदा स्टेशनों को बुकमार्क करें।',
    'saved.find_stations': 'स्टेशन खोजें',
    'saved.remove_title': 'सहेजा गया स्टेशन हटाएं',
    'saved.remove_confirm': 'क्या आप इस स्टेशन को अपनी सहेजी गई सूची से हटाना चाहते हैं?',

    // Station Card & General Components
    'card.available': 'उपलब्ध',
    'card.unavailable': 'व्यस्त',
    'card.book_slot': 'स्लॉट बुक करें',
    'card.from': 'से',
    'card.renewable': 'नवीकरणीय',
    'card.chargers': 'चार्जर',
    'card.reviews': 'समीक्षाएं',
    'card.min': 'मिनट',

    // Charging Screen
    'charging.title': 'चार्जिंग सत्र',
    'charging.ready': 'चार्ज करने के लिए तैयार',
    'charging.in_progress': 'चार्जिंग जारी है...',
    'charging.duration': 'अवधि',
    'charging.energy': 'ऊर्जा',
    'charging.cost': 'लागत',
    'charging.charger_power': 'चार्जर पावर',
    'charging.rate': 'दर',
    'charging.est_range': 'अनुमानित रेंज जुड़ी',
    'charging.clean_grid': 'स्वच्छ ऊर्जा ग्रिड',
    'charging.co2_avoided': 'CO₂ बचत',
    'charging.start_btn': '⚡ चार्जिंग सत्र शुरू करें',
    'charging.end_btn': 'चार्जिंग सत्र समाप्त करें',
    'charging.start_alert_title': 'चार्जिंग शुरू करें',
    'charging.start_alert_desc': 'शुरू करने से पहले सुनिश्चित करें कि आपका वाहन चार्जर से सही ढंग से जुड़ा हुआ है।',
    'charging.end_alert_title': 'चार्जिंग सत्र समाप्त करें',
    'charging.end_alert_desc': 'क्या आप वाकई अपना चार्जिंग सत्र समाप्त करना चाहते हैं?',
    'charging.continue': 'चार्जिंग जारी रखें',
    'charging.complete_title': 'चार्जिंग पूर्ण! 🎉',
    'charging.complete_sub': 'इकोवोल्ट के साथ स्वच्छ ऊर्जा अपनाने और हरित क्रांति में योगदान देने के लिए धन्यवाद! 🌿⚡',
    'charging.delivered': 'प्रदान की गई',
    'charging.total_cost': 'कुल लागत',
    'charging.ecopoints': 'इकोपॉइंट्स',
    'charging.receipt_note': 'एक गतिशील सत्र रसीद और हरित क्रेडिट अलर्ट आपकी सूचनाओं में सहेज दिया गया है!',
    'charging.view_reservations': 'सभी बुकिंग्स देखें',
    'charging.go_home': 'होम पर जाएं',

    // Station Detail Screen
    'station.details_title': 'स्टेशन विवरण',
    'station.saved': 'सहेजा गया',
    'station.save': 'सहेजें',
    'station.loading': 'स्टेशन लोड हो रहा है...',
    'station.not_found': 'स्टेशन नहीं मिला',
    'station.go_back': 'वापस जाएं',
    'station.photos_enlarge': 'बड़ा करके देखने के लिए टैप करें',
    'station.no_photos': 'कोई फ़ोटो उपलब्ध नहीं है',
    'station.available_chargers': 'उपलब्ध चार्जर',
    'station.no_chargers': 'कोई चार्जर उपलब्ध नहीं है',
    'station.distance': 'दूरी',
    'station.min_drive': 'मिनट की ड्राइव',
    'station.rating': 'रेटिंग',
    'station.amenities': 'सुविधाएं',
    'station.get_directions': 'दिशा-निर्देश प्राप्त करें',
    'station.live_greenness': 'लाइव ग्रिड ग्रीननेस',
    'station.renewable': 'नवीकरणीय',
    'station.carbon_free': 'कार्बन-मुक्त',
    'station.carbon_intensity': 'कार्बन तीव्रता',
    'station.renewable_note': 'नवीकरणीय ≠ कार्बन-मुक्त (परमाणु को छोड़कर)',
    'station.grid_mix': 'अभी ग्रिड का मिश्रण',
    'station.forecast_24h': '24 घंटे का हरित पूर्वानुमान',
    'station.best_window': 'सर्वोत्तम समय:',
    'station.forecast_saves': 'बचत ~₹',
    'station.forecast_highlight': '◼ हाइलाइट किया गया = सर्वोत्तम चार्जिंग समय',
    'station.forecast_now': '◉ = अभी',
    'station.reserve_now': 'अभी स्लॉट बुक करें',
    'station.base_tariff': 'मूल टैरिफ',
    'station.service_markup': 'सेवा शुल्क',
    'station.green_discount_now': '🌿 हरित छूट (अभी)',
    'station.peak_surcharge': '⚡ पीक अधिभार',
    'station.no_tou_adj': 'कोई समायोजन नहीं',
    'station.final_price': 'अंतिम दर',
    'station.estimate': 'अनुमानित',
    'station.amenity.wifi': 'वाई-फाई',
    'station.amenity.restrooms': 'शौचालय',
    'station.amenity.cafe': 'कैफे',
    'station.amenity.shopping': 'शॉपिंग',
    'station.amenity.parking': 'पार्किंग',
    'station.amenity.24h': '24/7 पहुंच',
    'station.amenity.food_court': 'फूड कोर्ट',

    // Reserve & Booking Screen
    'reserve.title': 'चार्जर आरक्षित करें',
    'reserve.loading_charger': 'चार्जर विवरण लोड हो रहा है...',
    'reserve.charger_not_found': 'चार्जर नहीं मिला',
    'reserve.error_subtext': 'कृपया वापस जाएं और पुनः प्रयास करें',
    'reserve.select_vehicle': 'वाहन चुनें',
    'reserve.add_vehicle': '+ वाहन जोड़ें',
    'reserve.no_vehicles': 'आपके गैरेज में कोई वाहन नहीं मिला।',
    'reserve.select_date': 'तारीख चुनें',
    'reserve.select_time': 'शुरुआती समय चुनें',
    'reserve.duration': 'अवधि',
    'reserve.summary_title': 'बुकिंग सारांश',
    'reserve.date': 'तारीख',
    'reserve.time': 'समय',
    'reserve.duration_label': 'अवधि',
    'reserve.base_rate': 'मूल दर',
    'reserve.green_discount': '🌿 हरित छूट',
    'reserve.peak_surcharge_label': '⚡ पीक अधिभार',
    'reserve.effective_rate': 'प्रभावी दर',
    'reserve.estimated_cost': 'अनुमानित लागत',
    'reserve.cost_note': '85% चार्जिंग दक्षता पर पूरी अवधि के आधार पर',
    'reserve.confirm_btn': 'बुकिंग की पुष्टि करें',
    'reserve.select_time_alert': 'कृपया अपनी बुकिंग के लिए शुरुआती समय चुनें।',
    'reserve.no_vehicle_alert': 'आरक्षण करने से पहले कृपया अपनी प्रोफ़ाइल में एक वाहन जोड़ें।',
    'reserve.failed_alert': 'समय स्लॉट पहले से ही बुक हो सकता है या चार्जर अनुपलब्ध है। कृपया भिन्न समय चुनें।',
    'reserve.status_available': 'उपलब्ध',
    'reserve.status_in_use': 'व्यस्त',
    'reserve.status_reserved': 'आरक्षित',
    'reserve.status_offline': 'ऑफ़लाइन',
    'reserve.status_maintenance': 'रखरखाव',
    'reserve.type_dc_fast': 'डीसी फास्ट चार्जिंग',
    'reserve.type_level_2': 'लेवल 2 एसी',
    'reserve.type_tesla': 'टेस्ला सुपरचार्जर',
    'reserve.green_active': '🌿 हरित छूट सक्रिय — बचत',
    'reserve.peak_active': '⚡ पीक ऑवर — अधिभार',
    // Filter & Navigation Modals
    'filter.title': 'फ़िल्टर',
    'filter.reset': 'रीसेट',
    'filter.available_only': 'केवल उपलब्ध चार्जर',
    'filter.available_desc': 'केवल उपलब्ध चार्जर वाले स्टेशन दिखाएं',
    'filter.max_distance': 'अधिकतम दूरी',
    'filter.charger_type': 'चार्जर का प्रकार',
    'filter.connector_type': 'कनेक्टर का प्रकार',
    'filter.price_per_kwh': 'प्रति kWh दर',
    'filter.amenities': 'सुविधाएं',
    'filter.apply': 'फ़िल्टर लागू करें',
    'nav.title': 'नेविगेशन',
    'reservations.starts_now': 'अभी शुरू हो रहा है! कृपया स्टेशन पर पहुंचें',
    'reservations.mins_remaining': 'मिनट स्लॉट में शेष',
    'reservations.check_in_start': '⚡ चेक इन / चार्जिंग सत्र शुरू करें',
    'reservations.send_reminder': '🔔 स्थिति अनुस्मारक भेजें',
    'reservations.book_again': 'पुनः बुक करें',
    'reservations.cancel_alert_title': 'बुकिंग रद्द करें',
    'reservations.cancel_alert_msg': 'क्या आप वाकई इस बुकिंग को रद्द करना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
    'reservations.keep_booking': 'बुकिंग बनाए रखें',
    'reservations.cancelled_success': 'आपकी बुकिंग रद्द कर दी गई है।',

    // Manager Console Hindi
    'manager.title': 'स्टेशन प्रबंधक हब',
    'manager.title_short': 'स्टेशन मैनेजर',
    'manager.online': 'ऑनलाइन',
    'manager.telemetry_loading': 'मैनेजर डेटा लोड हो रहा है...',
    'manager.total_revenue': 'कुल स्टेशन राजस्व',
    'manager.clean_power_delivered': 'प्रदत्त स्वच्छ ऊर्जा',
    'manager.green_share': 'हरित हिस्सेदारी',
    'manager.utilization_rate': 'नेटवर्क उपयोग दर',
    'manager.operational_status': 'परिचालन स्थिति',
    'manager.managed_stations': 'प्रबंधित स्टेशन',
    'manager.active_sessions': 'सक्रिय चार्जिंग सत्र',
    'manager.co2_avoided': 'कुल CO₂ उत्सर्जन में कमी',
    'manager.hubs': 'हब',
    'manager.live_now': 'अभी लाइव',
    'manager.onboard_station': '+ नया चार्जिंग हब जोड़ें',
    'manager.station_name': 'स्टेशन का नाम',
    'manager.address': 'पता',
    'manager.connectors': 'कनेक्टर्स',
    'manager.maintenance': 'रखरखाव',
    'manager.available': 'उपलब्ध',
    'manager.in_use': 'उपयोग में',
    'manager.toggle_maintenance': 'रखरखाव बदलें',
    'manager.pricing_rules_title': 'मूल्य निर्धारण नियम और ToU शुल्क',
    'manager.pricing_rules_desc': 'डायनामिक समय मूल्य निर्धारण और सर्ज दर',
    'manager.provider_base_rate': 'मूल दर',
    'manager.operator_markup': 'ऑपरेटर मार्जिन',
    'manager.final_driver_rate': 'अंतिम दर',
    'manager.dynamic_discount': 'डायनामिक छूट',
    'manager.occupancy_threshold': 'ऑक्यूपेंसी सीमा',
    'manager.add_pricing_rule': '+ नया नियम जोड़ें',
    'manager.edit_rule': 'नियम बदलें',
    'manager.save_rule': 'मूल्य नियम सहेजें',
    'manager.payout_bank_details': 'रेज़रपे पेआउट बैंक विवरण',
    'manager.payout_desc': 'ईवी चार्जिंग सत्रों से प्राप्त राशि इस बैंक खाते में स्वचालित रूप से जमा की जाती है।',
    'manager.account_holder_name': 'खाताधारक का नाम',
    'manager.bank_name': 'बैंक का नाम',
    'manager.account_number': 'खाता संख्या',
    'manager.ifsc_code': 'आईएफएससी कोड',
    'manager.alert_toggles': 'अलर्ट और सूचना विकल्प',
    'manager.outage_alerts': 'आउटेज और ऑफलाइन अलर्ट',
    'manager.email_alerts': 'ईमेल निपटान सारांश',
    'manager.save_payout_settings': '💾 बैंक और अलर्ट सेटिंग्स सहेजें',
    'manager.app_preferences': '🌐 ऐप प्राथमिकताएं और शासन',
    'manager.app_language': 'ऐप की भाषा / Language',
    'manager.appearance_theme': 'डार्क / लाइट थीम',
    'manager.sign_out': 'साइन आउट',
    'manager.sign_out_confirm': 'क्या आप स्टेशन मैनेजर से लॉग आउट करना चाहते हैं?',
    'manager.force_stop': 'सत्र रोकें',
    'manager.issue_refund': 'रिफंड जारी करें',
    'manager.free_stuck_connector': 'अनलॉक कनेक्टर',
    'manager.no_sessions': 'कोई सक्रिय सत्र नहीं',
    'manager.tab_analytics': 'मैनेजर हब',
    'manager.tab_sessions': 'लाइव सत्र',
    'manager.tab_pricing': 'मूल्य इंजन',
    'manager.tab_payout': 'ऑपरेटर प्रोफ़ाइल',

    // Admin Console Hindi
    'admin.title': 'नेटवर्क एडमिन कंसोल',
    'admin.grid_online': 'ग्रिड ऑनलाइन',
    'admin.subtext': 'प्लेटफ़ॉर्म शासन और परिचालन ऑडिट पोर्टल',
    'admin.loading': 'एडमिन डेटा लोड हो रहा है...',
    'admin.notice_title': 'सर्वर-अनिवार्य केवल-पढ़ने योग्य शासन',
    'admin.notice_desc': 'एडमिन भूमिका ड्राइवर और प्रबंधक डेटा पर केवल-पढ़ने की दृश्यता लागू करती है। स्टेशन लिस्टिंग, मूल्य निर्धारण या वॉलेट फंड का सीधा संपादन संबंधित प्रबंधक के पास रहता है।',
    'admin.live_load': 'कुल नेटवर्क लाइव लोड',
    'admin.aggregate_green_share': 'कुल हरित हिस्सेदारी',
    'admin.gross_revenue': 'प्लेटफ़ॉर्म सकल राजस्व',
    'admin.green_shifts': 'ग्रीन विंडोज़ शिफ्ट',
    'admin.footprint_title': 'प्लेटफ़ॉर्म उपस्थिति और डेटा स्रोत',
    'admin.registered_users': 'पंजीकृत उपयोगकर्ता',
    'admin.operator_networks': 'ऑपरेटर नेटवर्क',
    'admin.hub_registry': 'स्टेशन हब रजिस्ट्री',
    'admin.data_quality': 'डेटा स्रोत गुणवत्ता',
    'admin.clean_methodology_title': 'स्वच्छ ऊर्जा कार्यप्रणाली और वर्गीकरण',
    'admin.clean_methodology_desc': '• जलविद्युत वर्गीकरण: कार्बन लेखांकन को सुरक्षित रखने के लिए बड़े जलविद्युत को सौर/पवन से अलग ट्रैक किया जाता है।\n• कार्बन-मुक्त बनाम नवीकरणीय: सौर और पवन को 100% नवीकरणीय गिना जाता है; ग्रिड परमाणु/जलविद्युत कार्बन-मुक्त में गिने जाते हैं।',
    'admin.search_stations_placeholder': '🔍 स्टेशन, पता या ऑपरेटर खोजें...',
    'admin.add_station': '+ नया स्टेशन जोड़ें',
    'admin.approved': 'स्वीकृत',
    'admin.deactivated': 'निष्क्रिय',
    'admin.pricing_readonly': 'मूल्य (केवल पठनीय)',
    'admin.flag_deactivate': '🚩 फ़्लैग / निष्क्रिय करें',
    'admin.approve_activate': '✅ स्वीकृत और सक्रिय करें',
    'admin.delete': '🗑️ हटाएँ',
    'admin.search_users_placeholder': '🔍 नाम या ईमेल से खोजें...',
    'admin.add_user': '+ उपयोगकर्ता जोड़ें',
    'admin.govern_role': '🛡️ भूमिका बदलें',
    'admin.data_police_title': '📊 डेटा गुणवत्ता और विसंगति निगरानी',
    'admin.live_feed': 'लाइव एपीआई फीड',
    'admin.cached_snapshot': 'कैश्ड ग्रिड स्नैपशॉट',
    'admin.ml_forecast': 'पूर्वानुमानित हिस्सा',
    'admin.anomalies_detected': '0 विसंगतियां पाई गईं',
    'admin.system_ops_title': '⚡ सिस्टम संचालन स्थिति',
    'admin.server_uptime': 'सर्वर अपटाइम',
    'admin.postgres_latency': 'पोस्टग्रेएसक्यूएल विलंबता',
    'admin.maps_quota': 'गूगल मैप्स एपीआई कोटा उपयोग',
    'admin.ml_worker': 'एमएल प्रेडिक्शन वर्कर',
    'admin.booking_worker': 'बुकिंग रिमाइंडर वर्कर',
    'admin.app_preferences': '🌐 एडमिन प्राथमिकताएं और शासन',
    'admin.app_language': 'प्लेटफ़ॉर्म भाषा / Language',
    'admin.appearance_theme': 'डार्क / लाइट थीम',
    'admin.sign_out': 'एडमिन खाते से साइन आउट करें',
    'admin.sign_out_confirm': 'क्या आप वाकई नेटवर्क एडमिन कंसोल से लॉग आउट करना चाहते हैं?',
    'admin.financials_title': '💰 नेटवर्क वित्तीय संचयी आंकड़े',
    'admin.financials_sub': 'वित्तीय डेटा केवल-पठनीय है। एडमिन सीधे वॉलेट को छुए बिना लेनदेन की निगरानी करते हैं।',
    'admin.total_volume': 'कुल भुगतान राशि',
    'admin.successful_tx': 'सफल लेन-देन',
    'admin.failed_tx_rate': 'विफल लेन-देन दर',
    'admin.refund_total': 'संसाधित कुल रिफंड',
    'admin.power_taxonomy': '⚙️ पावर प्रदाता वर्गीकरण',
    'admin.connector_taxonomy': '🔌 कनेक्टर प्रकार वर्गीकरण',
    'admin.greenness_thresholds': '🌿 हरित स्तर सीमाएं',
    'admin.security_events_title': '🔒 सुरक्षा कार्यक्रम और प्रमाणीकरण निगरानी',
    'admin.failed_logins': 'विफल लॉगिन प्रयास (24h)',
    'admin.signature_errors': 'अमान्य हस्ताक्षर त्रुटियां',
    'admin.rate_limit_hits': 'रेट-सीमा ट्रिगर संख्या',
    'admin.tab_overview': 'एडमिन हब',
    'admin.tab_registry': 'स्टेशन रजिस्ट्री',
    'admin.tab_users': 'उपयोगकर्ता शासन',
    'admin.tab_zones': 'ग्रिड एवं गुणवत्ता',
    'admin.tab_health': 'सिस्टम संचालन',
    'admin.tab_financials': 'वित्तीय डेटा',
    'admin.tab_config': 'प्लेटफॉर्म कॉन्फ़िगरेशन',
    'admin.tab_audit': 'ऑडिट ट्रेल',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => Promise<void>;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    async function loadLanguage() {
      try {
        const saved = await SecureStore.getItemAsync(LANGUAGE_STORAGE_KEY);
        if (saved === 'en' || saved === 'hi') {
          setLanguageState(saved);
        }
      } catch {}
    }
    loadLanguage();
  }, []);

  const setLanguage = useCallback(async (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      await SecureStore.setItemAsync(LANGUAGE_STORAGE_KEY, lang);
    } catch {}
  }, []);

  const t = useCallback(
    (key: string, fallback?: string): string => {
      const dict = translations[language];
      if (dict && dict[key]) {
        return dict[key];
      }
      // Fallback to English dictionary
      if (translations.en[key]) {
        return translations.en[key];
      }
      return fallback || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
}
