"use strict";
// ──────────────────────────────────────────────────────────────
// /contracts/enums.ts
// Shared enums for ecoVolt-finder.
// ALL THREE MEMBERS import from here — never duplicate locally.
// Changes require a review from all 3 members before merge.
// ──────────────────────────────────────────────────────────────
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataQuality = exports.GreennessBand = exports.SessionStatus = exports.PowerProvider = exports.VehicleClass = exports.ConnectorType = exports.Role = void 0;
var Role;
(function (Role) {
    Role["DRIVER"] = "driver";
    Role["MANAGER"] = "manager";
    Role["ADMIN"] = "admin";
})(Role || (exports.Role = Role = {}));
var ConnectorType;
(function (ConnectorType) {
    ConnectorType["CCS2"] = "ccs2";
    ConnectorType["CHADEMO"] = "chademo";
    ConnectorType["TYPE2_AC"] = "type2_ac";
    ConnectorType["BHARAT_DC_001"] = "bharat_dc_001";
    ConnectorType["BHARAT_AC_001"] = "bharat_ac_001";
    ConnectorType["THREE_PIN"] = "three_pin";
})(ConnectorType || (exports.ConnectorType = ConnectorType = {}));
/** 2-wheeler vs 4-wheeler — affects range, efficiency, and travel cost */
var VehicleClass;
(function (VehicleClass) {
    VehicleClass["CAR"] = "car";
    VehicleClass["BIKE"] = "bike";
})(VehicleClass || (exports.VehicleClass = VehicleClass = {}));
/** Indian power distribution companies / providers */
var PowerProvider;
(function (PowerProvider) {
    PowerProvider["TORRENT"] = "torrent_power";
    PowerProvider["GUVNL_GB"] = "guvnl_gb";
    PowerProvider["ADANI"] = "adani_energy";
    PowerProvider["TATA"] = "tata_power";
    PowerProvider["BSES"] = "bses";
    PowerProvider["MSEDCL"] = "msedcl";
    PowerProvider["OTHER"] = "other";
})(PowerProvider || (exports.PowerProvider = PowerProvider = {}));
var SessionStatus;
(function (SessionStatus) {
    SessionStatus["RESERVED"] = "reserved";
    SessionStatus["SCHEDULED"] = "scheduled";
    SessionStatus["ACTIVE"] = "active";
    SessionStatus["COMPLETED"] = "completed";
    SessionStatus["CANCELLED"] = "cancelled";
    SessionStatus["EXPIRED"] = "expired";
    SessionStatus["FAILED"] = "failed";
})(SessionStatus || (exports.SessionStatus = SessionStatus = {}));
/**
 * Renewable-% band — maps renewablePct to a human/visual label.
 *   >=80 VERY_HIGH · 65-79 HIGH · 50-64 MEDIUM · 35-49 (no label, amber)
 *   20-34 LOW · <20 VERY_LOW
 */
var GreennessBand;
(function (GreennessBand) {
    GreennessBand["VERY_HIGH"] = "very_high";
    GreennessBand["HIGH"] = "high";
    GreennessBand["MEDIUM"] = "medium";
    GreennessBand["LOW"] = "low";
    GreennessBand["VERY_LOW"] = "very_low";
})(GreennessBand || (exports.GreennessBand = GreennessBand = {}));
/**
 * Provenance tag on every grid / greenness value.
 * The app always shows this to the user — we never hide uncertainty.
 *   live     – straight from the API, recent
 *   cached   – live data served from a short-TTL cache
 *   forecast – predicted value, carries confidence
 *   mock     – generated by the mock generator (no external call)
 *   stale    – cached data past its freshness threshold
 */
var DataQuality;
(function (DataQuality) {
    DataQuality["LIVE"] = "live";
    DataQuality["CACHED"] = "cached";
    DataQuality["FORECAST"] = "forecast";
    DataQuality["MOCK"] = "mock";
    DataQuality["STALE"] = "stale";
})(DataQuality || (exports.DataQuality = DataQuality = {}));
