// ──────────────────────────────────────────────────────────────
// /contracts/enums.ts
// Shared enums for ecoVolt-finder.
// ALL THREE MEMBERS import from here — never duplicate locally.
// Changes require a review from all 3 members before merge.
// ──────────────────────────────────────────────────────────────

export enum Role {
  DRIVER  = 'driver',
  MANAGER = 'manager',
  ADMIN   = 'admin',
}

export enum ConnectorType {
  CCS2           = 'ccs2',
  CHADEMO        = 'chademo',
  TYPE2_AC       = 'type2_ac',
  BHARAT_DC_001  = 'bharat_dc_001',
  BHARAT_AC_001  = 'bharat_ac_001',
  THREE_PIN      = 'three_pin',
}

/** 2-wheeler vs 4-wheeler — affects range, efficiency, and travel cost */
export enum VehicleClass {
  CAR  = 'car',
  BIKE = 'bike',
}

/** Indian power distribution companies / providers */
export enum PowerProvider {
  TORRENT  = 'torrent_power',
  GUVNL_GB = 'guvnl_gb',
  ADANI    = 'adani_energy',
  TATA     = 'tata_power',
  BSES     = 'bses',
  MSEDCL   = 'msedcl',
  OTHER    = 'other',
}

export enum SessionStatus {
  RESERVED  = 'reserved',
  SCHEDULED = 'scheduled',
  ACTIVE    = 'active',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
  EXPIRED   = 'expired',
  FAILED    = 'failed',
}

/**
 * Renewable-% band — maps renewablePct to a human/visual label.
 *   >=80 VERY_HIGH · 65-79 HIGH · 50-64 MEDIUM · 35-49 (no label, amber)
 *   20-34 LOW · <20 VERY_LOW
 */
export enum GreennessBand {
  VERY_HIGH = 'very_high',
  HIGH      = 'high',
  MEDIUM    = 'medium',
  LOW       = 'low',
  VERY_LOW  = 'very_low',
}

/**
 * Provenance tag on every grid / greenness value.
 * The app always shows this to the user — we never hide uncertainty.
 *   live     – straight from the API, recent
 *   cached   – live data served from a short-TTL cache
 *   forecast – predicted value, carries confidence
 *   mock     – generated by the mock generator (no external call)
 *   stale    – cached data past its freshness threshold
 */
export enum DataQuality {
  LIVE     = 'live',
  CACHED   = 'cached',
  FORECAST = 'forecast',
  MOCK     = 'mock',
  STALE    = 'stale',
}
